############################################################
# +------------------------------------------------------+ #
# |             Drewpercraft - BlockBank.jar             | #
# +------------------------------------------------------+ #
############################################################
announcements: true
savingsRate: 0
loanRate: -1
openHour: 8
closeHour: 17
maxVaults: 10
currencySymbol: $
currencySingular: dollar
currencyPlural: dollars
decimals: 2
dialogPrefix: &6
dialogSuffix: 
dropMoney: true

banks: