############################################################
# +------------------------------------------------------+ #
# |             Drewpercraft - BlockBank.jar             | #
# +------------------------------------------------------+ #
############################################################
# These optins apply to all banks and
# cannot be set in game
######################################
currencySymbol: $
currencySingular: dollar
currencyPlural: dollars
decimals: 2
dialogPrefix: &6
dialogSuffix: 
dropMoney: true
allowLoans: false
maxBranches: 5
logTransactions: true
maxOfflineDays: 3
abandonedCheck : false
abandonedAccountDays: 30
abandonedDistribution: even

######################################
# Branches with open/close set to 0/24
# can be set to fail randomly as if
# they are being serviced.
######################################
atmFailRate = 25
atmOfflineTime = 2000

######################################
# How ofter to save the player data
# files
######################################
#saveInterval: 10

######################################
# Banks can be limited to:
# world, faction, none
######################################
bankRelation: none

######################################
# The options apply to banks unless
# they are changed in the bank section
#######################################
announcements: true
savingsRate: 1
loanRate: 0


######################################
# The options apply to branches unless
# they are changed in the bank section
#######################################
openHour: 8
closeHour: 17


banks: