############################################################
# +------------------------------------------------------+ #
# |             Drewpercraft - BlockBank.jar             | #
# +------------------------------------------------------+ #
############################################################
# These optins apply to all banks
#################################
currencySymbol: $
currencySingular: dollar
currencyPlural: dollars
decimals: 2
dialogPrefix: &6
dialogSuffix: 
dropMoney: true
allowLoans: false
maxATM: 10
maxBranches: 3
#saveInterval: 10

######################################
# The options apply to banks unless
# they are changed in the bank section
#######################################
announcements: true
savingsRate: 0
loanRate: 0
mavVaults: 10

######################################
# The options apply to branches unless
# they are changed in the bank section
#######################################
openHour: 8
closeHour: 17
maxVaults: 10

banks: