############################################################
# +------------------------------------------------------+ #
# |             Drewpercraft - BlockBank.jar             | #
# +------------------------------------------------------+ #
############################################################
announcements: true
savingsRate: 0
loanRate: -1
openHour: 8
closeHour: 17
maxVaults: 10
currencySymbol: ©
currencySingular: coin
currencyPlural: coins
decimals: 0

banks: