############################################################
# +------------------------------------------------------+ #
# |             Drewpercraft - BlockBank.jar             | #
# +------------------------------------------------------+ #
############################################################
# These optins apply to all banks and
# cannot be set in game
######################################
currencySymbol: $
currencySingular: dollar
currencyPlural: dollars
decimals: 2
dialogPrefix: &6
dialogSuffix: 
dropMoney: true
allowLoans: false
maxBranches: 5
logTransactions: true
maxOfflineDays: 3
abandonedAccountDays: 30
abandonedDistribution: even

######################################
# How ofter to save the player data
# files
######################################
#saveInterval: 10

######################################
# Banks can be limited to:
# world, faction, none
######################################
bankRelation: none

######################################
# The options apply to banks unless
# they are changed in the bank section
#######################################
announcements: true
savingsRate: 1
loanRate: 0
maxVaults: 10

######################################
# The options apply to branches unless
# they are changed in the bank section
#######################################
openHour: 8
closeHour: 17
maxVaults: 10

banks: