name: BlockBank
author: hitechwizard
version: 2.0.0_SNAPSHOT
main: com.drewpercraft.blockbank.BlockBank
name: BlockBank
website: www.drewpercraft.com
description: A Realistic Banking system for cash and blocks
depend: [Vault, WorldGuard, WorldEdit]

commands:
    bank:
        description: Manage your bank accounts.
        usage: /bank [command] see /bank help for more info.
        permission: blockbank.admin
        permission-message: You must be an admin.
        aliases: [eco]
        
    branch:
        description: Manage bank branches.
        usage: /branch [bank name] see /branch help for more info.
        permission: blockbank.admin
        permission-message: You must be an admin
        
    balance:
        description: Get the balance in all your accounts.
        usage: /balance
        aliases: [bal, money, $]

    pay:
        description: Pay another player out of your pocket.
        usage: /pay [player] [amount]
        
    deposit:
        description: Deposit money into your bank account.
        permission: blockbank.user
        permission-message: You are not authorized to use banking services.
        usage: /deposit [amount]
    
    withdraw:
        description: Withdraw money from your bank account.
        permission: blockbank.user
        permission-message: You are not authorized to use banking services.
        usage: /withdraw [amount]
        
    borrow:
        description: Borrow money from the bank.
        permission: blockbank.loan
        permission-message: You are not authorized to borrow money.
        usage: /borrow [amount]
        
    credit:
        description: Determine how much the bank is willing to lend you.
        permission: blockbank.loan
        usage: /credit

    balancetop:
        description: Show your ranking in cash assets along with the top 10 players.
        usage: /balancetop
        aliases: [baltop]


permissions:
    blockbank.*:
        description: Gives user access to all Bank commands
        children:
            blockbank.user: true
            blockbank.vault: true
            blockbank.borrow: true
            blockbank.admin: true
              
    blockbank.user:
        description: Allow user to access BlockBank accounts
        default: true
        
    blockbank.vault:
        description: Allow user to use BlockBank vaults.
        default: true

    blockbank.borrow:
        description: Allow user to borrow money from BlockBank.
        default: true
          
    blockbank.admin:
        description: Allows user to administer BlockBank.
        default: op