name: BlockBank
author: hitechwizard
version: 2.0.0_SNAPSHOT
main: com.drewpercraft.blockbank.BlockBank
name: BlockBank
website: www.drewpercraft.com
description: A Realistic Banking system for cash and blocks
depend: [Vault, WorldGuard, WorldEdit]

commands:
    bank:
        description: Manage your bank accounts.
        usage: /bank [command] see /bank help for more info.
        permission: blockbank.user
        permission-message: You can not have a bank account.
        aliases: [eco]
        
    balance:
        description: Get the balance in all your accounts.
        usage: /balance
        aliases: [bal, money, $]

    pay:
        description: Pay another player out of your pocket.
        usage: /pay [player] [amount]

    balancetop:
        description: Show your ranking in cash assets along with the top 10 players.
        usage: /balancetop
        aliases: [baltop]


permissions:
    blockbank.*:
        description: Gives user access to all Bank commands
        children:
            blockbank.user: true
            blockbank.vault: true
            blockbank.borrow: true
            blockbank.admin: true
              
    blockbank.user:
        description: Allow user to access BlockBank accounts
        default: true
        
    blockbank.vault:
        description: Allow user to use BlockBank vaults.
        default: true

    blockbank.borrow:
        description: Allow user to borrow money from BlockBank.
        default: true
          
    blockbank.admin:
        description: Allows user to administer BlockBank.
        default: op